<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ORACLEO-61EKHM7" failures="1" tests="5" name="Test" time="86.847" errors="0" timestamp="2024-08-15T14:01:11 IST">
  <testcase classname="com.qa.Testcases.LoginTest" name="verifyPageTitle" time="1.247"/>
  <testcase classname="com.qa.Testcases.LoginTest" name="verifyForgotPass" time="32.405"/>
  <testcase classname="com.qa.Testcases.LoginTest" name="verifyinvalidLoginLogout" time="1.876"/>
  <testcase classname="com.qa.Testcases.LoginTest" name="verifyLoginTest" time="0.518"/>
  <testcase classname="com.qa.Testcases.LoginTest" name="verifyThatGoto" time="64.587">
    <failure type="java.lang.AssertionError" message="expected [abc] but found [Cogmento CRM]">
      <![CDATA[java.lang.AssertionError: expected [abc] but found [Cogmento CRM]
at com.qa.Testcases.LoginTest.verifyThatGoto(LoginTest.java:62)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyThatGoto -->
</testsuite> <!-- Test -->
